### ISSUE TITLE
How to use it with NLTK?

### ISSUE THREAD

**Issue by mirfan899** [globalwordnet/english-wordnet#771]
**Is your feature request related to a problem? Please describe.**
I'm trying to use `english-wordnet-2021.zip` with NLTK. I have copied the files and placed it in `wordnet` directory of `nltk_data`

Some `synsets` works but when I try to use all the `synsets` it throws error which I am unable to fix.

Here is what it looks like.

```python
synsets = wordnet.all_synsets()
output = []
# for synset in synsets:
for index, synset in enumerate(synsets):
    try:
        print(wordnet.synset(synset._name).lemmas())
        for lemma in wordnet.synset(synset._name).lemmas():
            t = lemma.synset()._name.split(".")[1]
            key = lemma.key()
            print(key)
            r = str(wordnet.ss2of(lemma.synset()))
            offset = r[:r.index("-")]+t
            print(offset)
            output.append(key + " " + "wn:"+offset)
    except:
        print(synset , "name Not found==================================================")
```

For example word `agricultural` throws error.

```python
from nltk.corpus import wordnet
print(wordnet.synsets("agricultural"))
Traceback (most recent call last):
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1440, in _synset_from_pos_and_line
    columns_str, gloss = data_file_line.strip().split("|")
ValueError: too many values to unpack (expected 2)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1611, in synsets
    for p in pos
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1613, in <listcomp>
    for offset in index[form].get(p, [])
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1414, in synset_from_pos_and_offset
    synset = self._synset_from_pos_and_line(pos, data_file_line)
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1530, in _synset_from_pos_and_line
    head_lemma = synset.similar_tos()[0]._lemmas[0]
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 198, in similar_tos
    return self._related("&")
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1079, in _related
    r = [get_synset(pos, offset) for pos, offset in pointer_tuples]
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1079, in <listcomp>
    r = [get_synset(pos, offset) for pos, offset in pointer_tuples]
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1414, in synset_from_pos_and_offset
    synset = self._synset_from_pos_and_line(pos, data_file_line)
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1524, in _synset_from_pos_and_line
    raise WordNetError("line %r: %s" % (data_file_line, e)) from e
nltk.corpus.reader.wordnet.WordNetError: line '02020442 00 a 01 rural 0 011 ! 02022522 a 0101 + 04961506 n 0102 & 02020981 a 0000 & 02021158 a 0000 & 02021320 a 0000 & 02021613 a 0000 & 02021727 a 0000 & 02021895 a 0000 & 02022057 a 0000 & 02022225 a 0000 & 02022388 a 0000 | of or relating to the countryside as opposed to the city; living in or characteristic of farming or country life| living in or characteristic of farming or country life; rural people; large rural households; unpaved rural roads; an economy that is basically rural; rural electrification; rural free delivery  \n': too many values to unpack (expected 2)
```
After removing the extra `|`, at line 11279 of `data.adj`, it throws another error.

```python
from nltk.corpus import wordnet
print(wordnet.synsets("agricultural"))
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1611, in synsets
    for p in pos
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1613, in <listcomp>
    for offset in index[form].get(p, [])
  File "/home/irfan/environments/ewiser/lib/python3.6/site-packages/nltk/corpus/reader/wordnet.py", line 1419, in synset_from_pos_and_offset
    raise WordNetError("No WordNet synset found for pos={0} at offset={1}.".format(pos,offset))
nltk.corpus.reader.wordnet.WordNetError: No WordNet synset found for pos=a at offset=2020981.
```

**Describe the solution you'd like**
Is there a way to use it with `NLTK` properly.

**Describe alternatives you've considered**

**Additional context**

**Comment by jmccrae** [comment]
My understanding is that support is under development from the NLTK team. I think @ekaf can comment in more detail.

**Comment by ekaf** [comment]
It is still too early to use the EWN 2021 release candidate with NLTK, because issues are being fixed just these days. The situation is already much improved with the very latest release though. There are more details under issue #747.

**Comment by mirfan899** [comment]
Okay, thanks. Will check later.

**Comment by arademaker** [comment]
Maybe you can consider using the new wn Python package?

https://github.com/goodmami/wn

**Comment by ekaf** [comment]
The 'develop' branch of NLTK now supports OEWN 2021 through https://github.com/nltk/nltk/pull/2860
