### ISSUE TITLE
The 2019 edition RDF and WNDB download links do not work

### ISSUE THREAD

**Issue by rhdunn** [globalwordnet/english-wordnet#961]
**Describe the bug**
The download links for the 2019 edition RDF and WNDB format downloads do not work. They generate 500 errors when looking in the developer tab of a web browser.

**To Reproduce**
1. Go to the readme/GitHub code page of this project.
2. Click on the RDF or WNDB links for the 2019 edition.
3. No download is initiated by the browser.

**Expected behavior**
The coresponding RDF or WNDB file should be downloaded.

**Additional context**
Using gwn (https://github.com/jmccrae/gwn-scala-api) I get alot of lines like:
> Could not extract LEX ID from ewn-Regency_era-n-ewn-15320846-00

followed by:
```
Exception in thread "main" java.util.NoSuchElementException: key not found: The banks %s the check
        at scala.collection.MapLike.default(MapLike.scala:236)
        at scala.collection.MapLike.default$(MapLike.scala:235)
        at scala.collection.AbstractMap.default(Map.scala:65)
        at scala.collection.MapLike.apply(MapLike.scala:144)
        at scala.collection.MapLike.apply$(MapLike.scala:143)
        at scala.collection.AbstractMap.apply(Map.scala:65)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$writeData$40(wndb.scala:865)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$writeData$40$adapted(wndb.scala:865)
        at scala.collection.immutable.List.map(List.scala:293)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$writeData$36(wndb.scala:865)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$writeData$3(wndb.scala:843)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at org.globalwordnet.api.serialize.WNDB.writeData(wndb.scala:757)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$write$5(wndb.scala:527)
        at org.globalwordnet.api.serialize.WNDB.$anonfun$write$5$adapted(wndb.scala:523)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
        at org.globalwordnet.api.serialize.WNDB.write(wndb.scala:523)
        at org.globalwordnet.api.Main$.convertFormat(main.scala:400)
        at org.globalwordnet.api.Main$.main(main.scala:160)
        at org.globalwordnet.api.Main.main(main.scala)
```

**Comment by jmccrae** [comment]
Fixed
